[versions]
agp = "8.11.0"
android-compileSdk = "36"
android-minSdk = "23"
android-targetSdk = "36"
jdk = "17"
aboutLibraries = "12.2.4"
androidPdfViewer3 = "3.2.7"
androidx_activity = "1.11.0"
androidx_appcompat = "1.7.1"
androidx_core_ktx = "1.17.0"
androidx_datastore = "1.1.7"
androidx_lifecycle = "2.9.4"
androidx_media3 = "1.8.0"
androidx_test_junit = "1.3.0"
appUpdateKtx = "2.1.0"
haze = "1.6.10"
kaluga = "1.5.1"
coil = "3.3.0"
compose_material3 = "1.4.0"
compose_ui = "1.9.3"
composeBom = "2025.10.00"
composeHotReload = "1.0.0-rc02"

requerySqliteAndroid = "3.49.0"
slf4jApi = "2.0.17"
turbine = "1.2.1"
xmlutil = "0.91.2"
coroutines = "1.10.2"
coroutinesTest = "1.10.2"
dateTime = "0.7.1"
detekt = "1.23.8"
espresso = "3.7.0"
firebaseBom = "34.3.0"
firebaseCrashlyticsGradle = "3.0.6"
googleServices = "4.4.3"
jetbrainsCompose = "1.10.0-alpha02"
jetbrainsNavigation = "2.9.0"
jetbrainsViewModel = "2.9.4"
kotlin = "2.2.0"
kotlinInject = "0.8.0"
kotlinInjectAnvil = "0.1.6"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxIo = "0.8.0"
ktor = "3.3.0"
ktor-test = "2.3.13"
ksp = "2.2.0-2.0.2"
logback = "1.5.18"
androidxNavigation = "2.9.5"
okio = "3.16.0"
serialization = "1.9.0"
sqlDelight = "2.1.0"
test_junit = "4.13.2"
triplet = "3.12.1"
versions = "0.53.0"
anotherPdfViewer = "2.3.7"
uiViewbinding = "1.9.2"
fragmentCompose = "1.8.9"

[libraries]
android-pdf-viewer3 = { module = "com.github.marain87:AndroidPdfViewer", version.ref = "androidPdfViewer3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx_appcompat" }
androidx-fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "fragmentCompose" }
androidx-media3-common-ktx = { module = "androidx.media3:media3-common-ktx", version.ref = "androidx_media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx_media3" }
androidx-media3-exoplayer-midi = { module = "androidx.media3:media3-exoplayer-midi", version.ref = "androidx_media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "androidx_media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx_media3" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx_core_ktx" }
androidx-lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx_lifecycle" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "androidx_datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx_datastore" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }

about-libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
about-libraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose-core", version.ref = "aboutLibraries" }
about-libraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
kaluga-base = { module = "com.splendo.kaluga:base", version.ref = "kaluga" }
kaluga-media = { module = "com.splendo.kaluga:media", version.ref = "kaluga" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose_material3" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx_activity" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines" }
coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
kotlin-inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime-kmp", version.ref = "kotlinInject" }
kotlin-inject-anvil-compiler = { module = "software.amazon.lastmile.kotlin.inject.anvil:compiler", version.ref = "kotlinInjectAnvil" }
kotlin-inject-anvil-runtime = { module = "software.amazon.lastmile.kotlin.inject.anvil:runtime", version.ref = "kotlinInjectAnvil" }
kotlin-inject-anvil-runtime-optional = { module = "software.amazon.lastmile.kotlin.inject.anvil:runtime-optional", version.ref = "kotlinInjectAnvil" }
kotlin-inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "dateTime" }
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin" }
ktor-client-js = { module = "io.ktor:ktor-client-js" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-tests = { module = "io.ktor:ktor-server-tests-jvm", version.ref = "ktor-test" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
sqldelight-coroutines-extensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqlDelight" }
sqldelight-adapters = { group = "app.cash.sqldelight", name = "primitive-adapters", version.ref = "sqlDelight" }
sqldelight-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqlDelight" }
sqldelight-native = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqlDelight" }
sqldelight-jvm = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqlDelight" }
requery-sqlite-android = { module = "com.github.requery:sqlite-android", version.ref = "requerySqliteAndroid" }
squareup-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
squareup-okio-fakefilesystem = { group = "com.squareup.okio", name = "okio-fakefilesystem", version.ref = "okio" }
cashapp-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }

coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

jetbrains-material-compose = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrainsCompose" }
jetbrains-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrainsNavigation" }
jetbrains-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrainsViewModel" }
jetbrains-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrainsViewModel" }

pdf-viewer = { module = "io.github.afreakyelf:Pdf-Viewer", version.ref = "anotherPdfViewer" }

test-androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx_test_junit" }
test-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose_ui" }
test-ui-tooling-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
test-junit = { group = "junit", name = "junit", version.ref = "test_junit" }
test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "uiViewbinding" }

[bundles]
media3 = ["androidx-media3-exoplayer", "androidx-media3-ui", "androidx-media3-session", "androidx-media3-common-ktx", "androidx-media3-exoplayer-midi"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose-hotreload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
jetbrains-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
androidx-navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
triplet-play = { id = "com.github.triplet.play", version.ref = "triplet" }
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
